# Generated by Django 4.0 on 2021-12-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='shop',
            new_name='pcs',
        ),
    ]
