# Generated by Django 4.0.1 on 2022-01-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название региона'),
        ),
        migrations.AlterField(
            model_name='region',
            name='square',
            field=models.IntegerField(blank=True, verbose_name='Площадь территорий'),
        ),
    ]
